FROM frolvlad/alpine-glibc:alpine-3.12

COPY bin/entrypoint /bin/entrypoint

RUN apk add --no-cache curl && \
    curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.3.0 && \
    mv /root/.deno/bin/deno /bin/deno

ENTRYPOINT [ "entrypoint" ]
CMD ["run", "https://deno.land/std/examples/welcome.ts"]
